In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [2]:
frame = pd.read_csv("./course-files/mcdonalds.csv", usecols=['Item','Category','Serving Size','Calories','TotalFat'])

In [7]:
calories400 = frame['Calories'] >= 400

In [4]:
(frame['TotalFat']<=20).head()

0     True
1     True
2    False
3    False
4    False
Name: TotalFat, dtype: bool

In [6]:
totalFatLess20 = frame['TotalFat'] <=20

In [8]:
frame[calories400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [9]:
frame[totalFatLess20].head()

,Category,Item,Serving Size,Calories,TotalFat
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,13.0
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,8.0
8,Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (R...",5.4 oz (153 g),410,20.0
16,Breakfast,Southern Style Chicken Biscuit (Regular Biscuit),5 oz (143 g),410,20.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0

In [11]:
frame[frame['Calories']>=400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [12]:
isBreakfast = frame["Category"] == "Breakfast"

In [13]:
frame[isBreakfast & calories400].head()

,Category,Item,Serving Size,Calories,TotalFat
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,28.0
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,23.0
5,Breakfast,Steak & Egg McMuffin,6.5 oz (185 g),430,23.0
6,Breakfast,"Bacon, Egg & Cheese Biscuit (Regular Biscuit)",5.3 oz (150 g),460,26.0
7,Breakfast,"Bacon, Egg & Cheese Biscuit (Large Biscuit)",5.8 oz (164 g),520,30.0

In [16]:
frame[isBreakfast & calories400 & totalFatLess20]

,Category,Item,Serving Size,Calories,TotalFat
8,Breakfast,"Bacon, Egg & Cheese Biscuit with Egg Whites (R...",5.4 oz (153 g),410,20.0
16,Breakfast,Southern Style Chicken Biscuit (Regular Biscuit),5 oz (143 g),410,20.0
20,Breakfast,"Bacon, Egg & Cheese McGriddles with Egg Whites",6.3 oz (178 g),400,15.0
39,Breakfast,Cinnamon Melts,4 oz (114 g),460,19.0

In [17]:
frame[~ isBreakfast].head()

,Category,Item,Serving Size,Calories,TotalFat
42,Beef & Pork,Big Mac,7.4 oz (211 g),530,27.0
43,Beef & Pork,Quarter Pounder with Cheese,7.1 oz (202 g),520,26.0
44,Beef & Pork,Quarter Pounder with Bacon & Cheese,8 oz (227 g),600,29.0
45,Beef & Pork,Quarter Pounder with Bacon Habanero Ranch,8.3 oz (235 g),610,31.0
46,Beef & Pork,Quarter Pounder Deluxe,8.6 oz (244 g),540,27.0

In [18]:
color = ['green', 'green','blue','blue','red','red','white']
size = ['S','S','S','M','M','M','L']
gender = ['M','W','M','W','M','W','U']
clothes = pd.DataFrame({'color':color,'size':size,'gender':gender})
clothes

   color size gender
0  green    S      M
1  green    S      W
2   blue    S      M
3   blue    M      W
4    red    M      M
5    red    M      W
6  white    L      U