In [1]:
import pandas as pd
import numpy as np

In [2]:
products = pd.read_csv('./course-files/WA_Sales_Products_2012-14.csv')

In [3]:
products.head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
0,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548
1,United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Double Flame,2012,Q1 2012,35950.32,252,0.474274
2,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Dome,2012,Q1 2012,89940.48,147,0.352772
3,United States,Fax,Outdoors Shop,Camping Equipment,Tents,Star Gazer 2,2012,Q1 2012,165883.41,303,0.282938
4,United States,Fax,Outdoors Shop,Camping Equipment,Sleeping Bags,Hibernator Lite,2012,Q1 2012,119822.20,1415,0.291450

In [6]:
groups = products.groupby(by='Retailer country')

In [7]:
type(groups)

pandas.core.groupby.generic.DataFrameGroupBy

In [9]:
len(groups)

21

In [10]:
groups.size()

Retailer country
Australia         3665
Austria           3862
Belgium           3710
Brazil            3288
Canada            5923
China             3652
Denmark           2358
Finland           3409
France            5779
Germany           5397
Italy             4018
Japan             5359
Korea             3399
Mexico            3845
Netherlands       4199
Singapore         3443
Spain             3557
Sweden            2925
Switzerland       4103
United Kingdom    5102
United States     7482
dtype: int64

In [11]:
groups.first()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2161.34,53,0.509564
Austria,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Analog,2012,Q1 2012,6562.30,137,0.373695
Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
Brazil,Web,Golf Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,15987.00,219,0.419206
Canada,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,12045.00,165,0.418630
China,Fax,Golf Shop,Golf Equipment,Irons,Hailstorm Steel Irons,2012,Q1 2012,69057.80,214,0.315153
Denmark,Web,Golf Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,2482.00,34,0.418630
Finland,Web,Department Store,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,16007.34,2586,0.526656
France,Fax,Golf Shop,Golf Equipment,Irons,Lady Hailstorm Steel Irons,2012,Q1 2012,19530.81,39,0.445356
Germany,Mail,Warehouse Store,Camping Equipment,Cooking Gear,TrailChef Cook Set,2012,Q1 2012,21197.46,402,0.336810
Italy,Fax,Outdoors Shop,Mountaineering Equipment,Rope,Husky Rope 50,2012,Q1 2012,18950.40,126,0.329056
Japan,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,28009.45,7091,0.465823
Korea,Telephone,Sports Store,Camping Equipment,Cooking Gear,TrailChef Canteen,2012,Q1 2012,12390.90,1030,0.449709
Mexico,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,4620.00,21,0.474727
Netherlands,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Cup,2012,Q1 2012,4213.85,1187,0.760563
Singapore,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Cook Set,2012,Q1 2012,49777.12,944,0.336810
Spain,Fax,Sports Store,Camping Equipment,Cooking Gear,TrailChef Water Bag,2012,Q1 2012,12191.58,1926,0.537125
Sweden,E-mail,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Kettle,2012,Q1 2012,12371.30,965,0.601404
Switzerland,Fax,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,5500.00,25,0.473455
United Kingdom,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,41205.00,570,0.419461
United States,Fax,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Deluxe Cook Set,2012,Q1 2012,59628.66,489,0.347548

In [12]:
products[products['Retailer country'] == 'Australia'].head(1)

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
3735,Australia,Telephone,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2161.34,53,0.509564

In [13]:
products[products['Retailer country'] == 'Canada'].head(1)

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
864,Canada,Fax,Outdoors Shop,Personal Accessories,Watches,Venue,2012,Q1 2012,12045.0,165,0.41863

In [14]:
groups.last()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
Retailer country,,,,,,,,,,
Australia,Sales visit,Department Store,Golf Equipment,Putters,Blue Steel Putter,2014,Q3 2014,14248.39,169,0.511327
Austria,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,11759.84,2194,0.524254
Belgium,Web,Sports Store,Personal Accessories,Navigation,Astro Pilot,2014,Q3 2014,33294.00,93,0.350754
Brazil,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,8066.80,1505,0.524254
Canada,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,13753.76,2566,0.524254
China,Web,Sports Store,Outdoor Protection,First Aid,Calamine Relief,2014,Q3 2014,408.00,68,0.528333
Denmark,Web,Sports Store,Personal Accessories,Binoculars,Ranger Vision,2014,Q3 2014,8788.00,52,0.533432
Finland,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,14380.88,2683,0.524254
France,Sales visit,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,10001.76,1866,0.524254
Germany,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,9669.44,1804,0.524254
Italy,Sales visit,Outdoors Shop,Mountaineering Equipment,Safety,Granite Climbing Helmet,2014,Q3 2014,56802.40,808,0.252632
Japan,Sales visit,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,12070.72,2252,0.524254
Korea,Sales visit,Golf Shop,Outdoor Protection,Sunscreen,Sun Shield,2014,Q3 2014,2292.00,382,0.540000
Mexico,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,14804.32,2762,0.524254
Netherlands,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,15088.40,2815,0.524254
Singapore,Web,Outdoors Shop,Personal Accessories,Navigation,Sky Pilot,2014,Q3 2014,10024.00,28,0.358715
Spain,Sales visit,Outdoors Shop,Mountaineering Equipment,Tools,Granite Extreme,2014,Q3 2014,89376.00,1176,0.387895
Sweden,Sales visit,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,6399.84,1194,0.524254
Switzerland,Web,Sports Store,Golf Equipment,Golf Accessories,Course Pro Gloves,2014,Q3 2014,8425.92,1572,0.524254
United Kingdom,Sales visit,Outdoors Shop,Personal Accessories,Navigation,Glacier GPS Extreme,2014,Q3 2014,45093.84,132,0.483432
United States,Sales visit,Eyewear Store,Personal Accessories,Binoculars,Seeker 35,2014,Q3 2014,83324.99,833,0.288314

In [15]:
groups.groups

{'Australia': Int64Index([ 3735,  3736,  3737,  3738,  3739,  3740,  3741,  3742,  3743,
              3744,
             ...
             85857, 85858, 85859, 85860, 85861, 85862, 85863, 85864, 85865,
             85866],
            dtype='int64', length=3665),
 'Austria': Int64Index([ 7588,  7589,  7590,  7591,  7592,  7593,  7594,  7595,  7596,
              7597,
             ...
             88073, 88074, 88075, 88076, 88077, 88078, 88079, 88080, 88081,
             88082],
            dtype='int64', length=3862),
 'Belgium': Int64Index([ 7270,  7271,  7272,  7273,  7274,  7275,  7276,  7277,  7278,
              7279,
             ...
             87859, 87860, 87861, 87862, 87863, 87864, 87865, 87866, 87867,
             87868],
            dtype='int64', length=3710),
 'Brazil': Int64Index([ 1833,  1834,  1835,  1836,  1837,  1838,  1839,  1840,  1841,
              1842,
             ...
             84729, 84730, 84731, 84732, 84733, 84734, 84735, 84736, 84737,
             84738],
            dtype='int64', length=3288),
 'Canada': Int64Index([  864,   865,   866,   867,   868,   869,   870,   871,   872,
               873,
             ...
             84358, 84359, 84360, 84361, 84362, 84363, 84364, 84365, 84366,
             84367],
            dtype='int64', length=5923),
 'China': Int64Index([ 3403,  3404,  3405,  3406,  3407,  3408,  3409,  3410,  3411,
              3412,
             ...
             85662, 85663, 85664, 85665, 85666, 85667, 85668, 85669, 85670,
             85671],
            dtype='int64', length=3652),
 'Denmark': Int64Index([ 4695,  4696,  4697,  4698,  4699,  4700,  4701,  4702,  4703,
              4704,
             ...
             86350, 86351, 86352, 86353, 86354, 86355, 86356, 86357, 86358,
             86359],
            dtype='int64', length=2358),
 'Finland': Int64Index([ 4913,  4914,  4915,  4916,  4917,  4918,  4919,  4920,  4921,
              4922,
             ...
             86541, 86542, 86543, 86544, 86545, 86546, 86547, 86548, 86549,
             86550],
            dtype='int64', length=3409),
 'France': Int64Index([ 5205,  5206,  5207,  5208,  5209,  5210,  5211,  5212,  5213,
              5214,
             ...
             86849, 86850, 86851, 86852, 86853, 86854, 86855, 86856, 86857,
             86858],
            dtype='int64', length=5779),
 'Germany': Int64Index([ 5807,  5808,  5809,  5810,  5811,  5812,  5813,  5814,  5815,
              5816,
             ...
             87156, 87157, 87158, 87159, 87160, 87161, 87162, 87163, 87164,
             87165],
            dtype='int64', length=5397),
 'Italy': Int64Index([ 7934,  7935,  7936,  7937,  7938,  7939,  7940,  7941,  7942,
              7943,
             ...
             88271, 88272, 88273, 88274, 88275, 88276, 88277, 88278, 88279,
             88280],
            dtype='int64', length=4018),
 'Japan': Int64Index([ 2146,  2147,  2148,  2149,  2150,  2151,  2152,  2153,  2154,
              2155,
             ...
             85069, 85070, 85071, 85072, 85073, 85074, 85075, 85076, 85077,
             85078],
            dtype='int64', length=5359),
 'Korea': Int64Index([ 3074,  3075,  3076,  3077,  3078,  3079,  3080,  3081,  3082,
              3083,
             ...
             85438, 85439, 85440, 85441, 85442, 85443, 85444, 85445, 85446,
             85447],
            dtype='int64', length=3399),
 'Mexico': Int64Index([ 1468,  1469,  1470,  1471,  1472,  1473,  1474,  1475,  1476,
              1477,
             ...
             84546, 84547, 84548, 84549, 84550, 84551, 84552, 84553, 84554,
             84555],
            dtype='int64', length=3845),
 'Netherlands': Int64Index([ 4072,  4073,  4074,  4075,  4076,  4077,  4078,  4079,  4080,
              4081,
             ...
             86085, 86086, 86087, 86088, 86089, 86090, 86091, 86092, 86093,
             86094],
            dtype='int64', length=4199),
 'Singapore': Int64Index([ 2750,  2751,  2752,  2753,  2754,  2755,  2756,  2757,  2758,
              2759,
             ...
             85250, 85251, 85252, 85253, 85254, 85255, 85256, 85257, 85258,
             85259],
            dtype='int64', length=3443),
 'Spain': Int64Index([ 8310,  8311,  8312,  8313,  8314,  8315,  8316,  8317,  8318,
              8319,
             ...
             88465, 88466, 88467, 88468, 88469, 88470, 88471, 88472, 88473,
             88474],
            dtype='int64', length=3557),
 'Sweden': Int64Index([ 4453,  4454,  4455,  4456,  4457,  4458,  4459,  4460,  4461,
              4462,
             ...
             86253, 86254, 86255, 86256, 86257, 86258, 86259, 86260, 86261,
             86262],
            dtype='int64', length=2925),
 'Switzerland': Int64Index([ 6318,  6319,  6320,  6321,  6322,  6323,  6324,  6325,  6326,
              6327,
             ...
             87380, 87381, 87382, 87383, 87384, 87385, 87386, 87387, 87388,
             87389],
            dtype='int64', length=4103),
 'United Kingdom': Int64Index([ 6696,  6697,  6698,  6699,  6700,  6701,  6702,  6703,  6704,
              6705,
             ...
             87667, 87668, 87669, 87670, 87671, 87672, 87673, 87674, 87675,
             87676],
            dtype='int64', length=5102),
 'United States': Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                 9,
             ...
             84044, 84045, 84046, 84047, 84048, 84049, 84050, 84051, 84052,
             84053],
            dtype='int64', length=7482)}

In [16]:
products.loc[groups.groups['Belgium']].head()

,Retailer country,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
7270,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
7271,Belgium,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Deluxe,2012,Q1 2012,5267.96,68,0.496579
7272,Belgium,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,22483.00,96,0.458979
7273,Belgium,Web,Golf Shop,Personal Accessories,Watches,TX,2012,Q1 2012,16100.00,87,0.448898
7274,Belgium,Web,Golf Shop,Personal Accessories,Eyewear,Polar Sun,2012,Q1 2012,2682.52,44,0.571075

In [17]:
groups.get_group('Belgium').head()

,Order method type,Retailer type,Product line,Product type,Product,Year,Quarter,Revenue,Quantity,Gross margin
7270,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Digital,2012,Q1 2012,2324.46,57,0.509564
7271,Web,Golf Shop,Personal Accessories,Watches,Mountain Man Deluxe,2012,Q1 2012,5267.96,68,0.496579
7272,Web,Golf Shop,Personal Accessories,Watches,Infinity,2012,Q1 2012,22483.00,96,0.458979
7273,Web,Golf Shop,Personal Accessories,Watches,TX,2012,Q1 2012,16100.00,87,0.448898
7274,Web,Golf Shop,Personal Accessories,Eyewear,Polar Sun,2012,Q1 2012,2682.52,44,0.571075