In [1]:
import pandas as pd
import numpy as np
incidents = pd.read_csv('./course-files/Canadian Railway Crossing Incidents.csv')
incidents.set_index(['Region','EventType'], inplace = True)
incidents.sort_index(inplace = True)

In [2]:
incidents.head()

                                   Public automated  Public passive  Private  \
Region           EventType
Alberta          Accidents                        3               7        2
                 Fatalities                       0               0        0
                 Serious injuries                 0               1        2
British Columbia Accidents                        4               1        0
                 Fatalities                       0               0        0

                                   Farm
Region           EventType
Alberta          Accidents            0
                 Fatalities           0
                 Serious injuries     0
British Columbia Accidents            0
                 Fatalities           0

In [3]:
incidents.stack().head()

Region   EventType
Alberta  Accidents   Public automated    3
                     Public passive      7
                     Private             2
                     Farm                0
         Fatalities  Public automated    0
dtype: int64

In [4]:
incidents.stack().to_frame().head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [5]:
stacked = incidents.stack().to_frame()

In [6]:
stacked.head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [7]:
stacked.unstack().head()

                                                 0
                                  Public automated Public passive Private Farm
Region           EventType
Alberta          Accidents                       3              7       2    0
                 Fatalities                      0              0       0    0
                 Serious injuries                0              1       2    0
British Columbia Accidents                       4              1       0    0
                 Fatalities                      0              0       0    0

In [8]:
stacked.unstack().unstack().head()

                                0                                             \
                 Public automated                             Public passive
EventType               Accidents Fatalities Serious injuries      Accidents
Region
Alberta                         3          0                0              7
British Columbia                4          0                3              1
Manitoba                        1          0                0              3
New Brunswick                   0          0                0              0
Newfoundland                    0          0                0              0

                                                                   \
                                               Private
EventType        Fatalities Serious injuries Accidents Fatalities
Region
Alberta                   0                1         2          0
British Columbia          0                0         0          0
Manitoba                  1                0         0          0
New Brunswick             0                0         0          0
Newfoundland              0                0         0          0


                                       Farm
EventType        Serious injuries Accidents Fatalities Serious injuries
Region
Alberta                         2         0          0                0
British Columbia                0         0          0                0
Manitoba                        0         2          0                1
New Brunswick                   0         0          0                0
Newfoundland                    0         0          0                0

In [9]:
stacked.unstack(0).head()

                                  0                                          \
Region                      Alberta British Columbia Manitoba New Brunswick
EventType
Accidents  Public automated       3                4        1             0
           Public passive         7                1        3             0
           Private                2                0        0             0
           Farm                   0                0        2             0
Fatalities Public automated       0                0        0             0

                                                                            \
Region                      Newfoundland Northwest Territories Nova Scotia
EventType
Accidents  Public automated            0                     0           1
           Public passive              0                     0           0
           Private                     0                     0           0
           Farm                        0                     0           0
Fatalities Public automated            0                     0           0


Region                      Ontario Quebec Saskatchewan
EventType
Accidents  Public automated       7      4            1
           Public passive         0      0            3
           Private                2      1            0
           Farm                   0      0            0
Fatalities Public automated       1      1            0